# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  llava-tgi-service:
    image: ghcr.io/huggingface/tgi-gaudi:2.3.1
    container_name: llava-tgi-service
    ports:
      - "5027:80"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HABANA_VISIBLE_DEVICES: all
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    runtime: habana
    cap_add:
      - SYS_NICE
    ipc: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 6s
      retries: 20
    command: --model-id ${LLM_MODEL_ID} --max-input-length 4096 --max-total-tokens 8192
  lvm:
    image: ${REGISTRY:-opea}/lvm:${TAG:-latest}
    container_name: lvm-service
    ports:
      - "5050:9399"
    ipc: host
    environment:
      LVM_ENDPOINT: ${LVM_ENDPOINT}
      LVM_COMPONENT_NAME: "OPEA_TGI_LLAVA_LVM"
    depends_on:
      llava-tgi-service:
        condition: service_healthy

networks:
  default:
    driver: bridge
