# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  llava-service:
    image: ${REGISTRY:-opea}/lvm-llava:${TAG:-latest}
    container_name: llava-service
    ports:
      - "5028:8399"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8399/health"]
      interval: 30s
      timeout: 6s
      retries: 20
  lvm:
    image: ${REGISTRY:-opea}/lvm:${TAG:-latest}
    container_name: lvm-service
    ports:
      - "5051:9399"
    ipc: host
    environment:
      LVM_ENDPOINT: ${LVM_ENDPOINT}
      LVM_COMPONENT_NAME: "OPEA_LLAVA_LVM"
    depends_on:
      llava-service:
        condition: service_healthy

networks:
  default:
    driver: bridge
