# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  llm-textgen:
    build:
      dockerfile: comps/llms/src/text-generation/Dockerfile
    image: ${REGISTRY:-opea}/llm-textgen:${TAG:-latest}
  llm-textgen-gaudi:
    build:
      dockerfile: comps/llms/src/text-generation/Dockerfile.intel_hpu
    image: ${REGISTRY:-opea}/llm-textgen-gaudi:${TAG:-latest}
  llm-docsum:
    build:
      dockerfile: comps/llms/src/doc-summarization/Dockerfile
    image: ${REGISTRY:-opea}/llm-docsum-tgi:${TAG:-latest}
  llm-faqgen:
    build:
      dockerfile: comps/llms/src/faq-generation/Dockerfile
    image: ${REGISTRY:-opea}/llm-faqgen:${TAG:-latest}
  llm-eval:
    build:
      dockerfile: comps/llms/utils/lm-eval/Dockerfile
    image: ${REGISTRY:-opea}/llm-eval:${TAG:-latest}
  lvm-video-llama:
    build:
      dockerfile: comps/third_parties/video-llama/src/Dockerfile
    image: ${REGISTRY:-opea}/lvm-video-llama:${TAG:-latest}
  lvm-llava:
    build:
      dockerfile: comps/third_parties/llava/src/Dockerfile
    image: ${REGISTRY:-opea}/lvm-llava:${TAG:-latest}
  lvm-llava-gaudi:
    build:
      dockerfile: comps/third_parties/llava/src/Dockerfile.intel_hpu
    image: ${REGISTRY:-opea}/lvm-llava-gaudi:${TAG:-latest}
  lvm-predictionguard:
    build:
      dockerfile: comps/third_parties/predictionguard/src/Dockerfile
    image: ${REGISTRY:-opea}/lvm-predictionguard:${TAG:-latest}
  lvm-llama-vision:
    build:
      dockerfile: comps/third_parties/llama-vision/src/Dockerfile
    image: ${REGISTRY:-opea}/lvm-llama-vision:${TAG:-latest}
  lvm-llama-vision-tp:
    build:
      dockerfile: comps/third_parties/llama-vision/src/Dockerfile.tp
    image: ${REGISTRY:-opea}/lvm-llama-vision-tp:${TAG:-latest}
  lvm-llama-vision-guard:
    build:
      dockerfile: comps/third_parties/llama-vision/src/Dockerfile.guard
    image: ${REGISTRY:-opea}/lvm-llama-vision-guard:${TAG:-latest}
